HousingApp/Models/property.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.enquiries = new HashSet<enquiry>();
        }
    
        public int property_id { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public string town_city { get; set; }
        public int users_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enquiry> enquiries { get; set; }
        public virtual user user { get; set; }
    }
}

HousingApp/Controllers/propertiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HousingApp.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace HousingApp.Controllers
{
    public class propertiesController : Controller
    {
        private HousingAppEntities db = new HousingAppEntities();

        // GET: properties/index
        public ActionResult Index()
        {
            var properties = db.properties.Include(p => p.user);
            return View(properties.ToList());
        }

        // GET: properties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            property property = db.properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        public ActionResult inquire(property p)
        {
            Session["toID"] = p.users_id.ToString();
            Session["regarding"] = p.property_id.ToString();
            return RedirectToAction("create", "enquiries");
        }

        // GET: properties/Create
        public ActionResult Create()
        {
            ViewBag.users_id = new SelectList(db.users, "users_id", "username");
            return View();
        }

        // POST: properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "property_id,address_line1,address_line2,town_city,users_id")] property property)
        {
            if (ModelState.IsValid)
            {
                db.properties.Add(property);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.users_id = new SelectList(db.users, "users_id", "username", property.users_id);
            return View(property);
        }

        // GET: properties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            property property = db.properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            ViewBag.users_id = new SelectList(db.users, "users_id", "username", property.users_id);
            return View(property);
        }

        // POST: properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "property_id,address_line1,address_line2,town_city,users_id")] property property)
        {
            if (ModelState.IsValid)
            {
                db.Entry(property).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.users_id = new SelectList(db.users, "users_id", "username", property.users_id);
            return View(property);
        }

        // GET: properties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            property property = db.properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        // POST: properties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            property property = db.properties.Find(id);
            db.properties.Remove(property);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HousingApp/Views/properties/Create.cshtml
@model HousingApp.Models.property

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>property</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.address_line1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address_line1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address_line1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address_line2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address_line2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address_line2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.town_city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.town_city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.town_city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.users_id, "users_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("users_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.users_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HousingApp/Views/properties/Delete.cshtml
@model HousingApp.Models.property

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>property</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.address_line1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address_line1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address_line2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address_line2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.town_city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.town_city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HousingApp/Views/properties/Details.cshtml
@model HousingApp.Models.property

@{
    ViewBag.Title = "Details";
}
<br />


@using (Html.BeginForm("inquire", "properties", FormMethod.Post))
{
    
    <table>
        <tr>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.address_line1)
            </td>
            <td>
                @Html.DisplayFor(model => model.address_line1)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.address_line2)
            </td>
            <td>
                @Html.DisplayFor(model => model.address_line2)
            </td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.town_city)</td>
            <td>@Html.DisplayFor(model => model.town_city)</td>
        </tr>
        <td>
            <input type="submit" value="inquire" />
        </td>
    </table>

}


HousingApp/Views/properties/Edit.cshtml
@model HousingApp.Models.property

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>property</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.property_id)

        <div class="form-group">
            @Html.LabelFor(model => model.address_line1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address_line1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address_line1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address_line2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address_line2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address_line2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.town_city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.town_city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.town_city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.users_id, "users_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("users_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.users_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HousingApp/Views/properties/Index.cshtml
@model IEnumerable<HousingApp.Models.property>

@{
    ViewBag.Title = "Index";
}
<br />
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {


            <div class="col-sm">
                @Html.DisplayNameFor(model => model.address_line1)
                @Html.DisplayFor(modelItem => item.address_line1)
            </div>
            <div class="col-sm">
                @Html.DisplayNameFor(model => model.address_line2)
                @Html.DisplayFor(modelItem => item.address_line2)
            </div>
            <div class="col-sm">
                @Html.DisplayNameFor(model => model.town_city)
                @Html.DisplayFor(modelItem => item.town_city)
            </div>
            
            @Html.ActionLink("Details", "Details", new { id = item.property_id})


        }
    </div>
    </div>